### ISSUE TITLE
Saving out to folder with today's date... "%date:yyyy-MM-dd%"

### ISSUE THREAD

**Issue by TheShadowNYC** [MushroomFleet/DJZ-Nodes#6]
Hi Drift! Hope all is well - big fan of your content and now nodes!

I'm trying to understand how to bake in the "%date:yyyy-MM-dd%" into my file names so that each run it's placing them in a folder with current date etc. Doesn't seem to be working for anywhere I try and use it... just makes a literal folder labeled "%date:yyyy-MM-dd%". Thinking this just is not supported in the node pack?
<img width="720" alt="Screen Shot 2024-12-12 at 1 04 34 PM" src="https://github.com/user-attachments/assets/e5a5a9d2-02ef-4bb3-93f7-a243508f46e9" />

**Comment by MushroomFleet** [comment]
I am familiar with this behavior, so i decided to test it (it's quite an old and forgotten feature now)

![50c449dd894445ea7f4538fcb5a34504 (1)](https://github.com/user-attachments/assets/1b9316d6-4bc4-4e81-b1df-a3873db10018)

As shown, using the correct syntax (according to comfyUI wiki) it has no effect, regardless of if you use my node or not.
My node is meant for String based sub directory organization and this %THING% feature is a core comfyUI feature. This means that my node is not containing any code to support that, and it should be handled by ComfyUI - if it even works at all.

I'm unable to use that in my comfyUI and people point to the installation of one or more custom nodes that may affect it's function - this may be the case, but it's beyond my control.

**Comment by MushroomFleet** [comment]
Recommended Alternative:
![e00a6979e1f3a343ec803b1a9196149d](https://github.com/user-attachments/assets/09ad84b9-74c3-41c3-8621-33278c564795)

https://github.com/audioscavenger/save-image-extended-comfyui
